import streamlit as st
import os
from pathlib import Path
import re

# === CONFIGURATION ===
st.set_page_config(page_title="Hedge Fund Tips Reports", page_icon="📈", layout="wide")

# Define the base directory where outputs are stored
OUTPUTS_DIR = Path("outputs")

# === HELPER FUNCTIONS ===


def get_available_episodes():
    """
    Scans the outputs directory for folders matching 'episode_{num}'
    and checks if a report exists inside them.
    Returns a sorted list of episode numbers (descending).
    """
    episodes = []

    if not OUTPUTS_DIR.exists():
        return []

    # Iterate through all items in the output directory
    for item in OUTPUTS_DIR.iterdir():
        if item.is_dir() and item.name.startswith("episode_"):
            try:
                # Extract the episode number (e.g., "319" from "episode_319")
                ep_num = item.name.split("_")[1]

                # Verify the report file actually exists
                report_path = (
                    item / "transcripts" / f"hedge_fund_tips_episode_{ep_num}_report.md"
                )

                if report_path.exists():
                    episodes.append(ep_num)
            except IndexError:
                continue  # Skip folders that don't match the expected format

    # Sort episodes numerically descending (newest first)
    try:
        episodes.sort(key=lambda x: int(x), reverse=True)
    except ValueError:
        episodes.sort(reverse=True)  # Fallback if non-numeric ids exist

    return episodes


def load_report(episode_number):
    """Reads the markdown content for a specific episode."""
    path = (
        OUTPUTS_DIR
        / f"episode_{episode_number}"
        / "transcripts"
        / f"hedge_fund_tips_episode_{episode_number}_report.md"
    )
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


# === MAIN UI ===

# Sidebar
with st.sidebar:
    st.header("🗂️ Library")

    # Get list of episodes
    available_episodes = get_available_episodes()

    if not available_episodes:
        st.warning("No reports found in `outputs/`.")
        st.info("Run the notebook pipeline first to generate reports.")
        selected_episode = None
    else:
        # Dropdown selection
        selected_episode = st.selectbox("Select Episode:", available_episodes, index=0)

        st.markdown("---")
        st.caption(f"Found {len(available_episodes)} episodes.")

# Main Content Area
st.title("📈 Hedge Fund Tips Analysis")

if selected_episode:
    # Load content
    content = load_report(selected_episode)

    if content:
        # We create a container for the report
        with st.container():
            # Render the markdown
            # unsafe_allow_html=True is useful if your markdown has raw HTML tables or color formatting
            st.markdown(content, unsafe_allow_html=True)
    else:
        st.error(
            f"Error: Report file for Episode {selected_episode} was found during scan but could not be loaded."
        )
else:
    # Empty state
    st.info("👈 Please select an episode from the sidebar to view the analysis.")

# Footer
st.markdown("---")
st.caption("Generated by AI Analyst Pipeline")
